name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Configure AWS credentials using secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Log in to AWS ECR
        env:
          AWS_REGION: ap-southeast-2
          AWS_ACCOUNT_ID: 039612872662
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t beyond/temp .

      - name: Tag Docker image
        env:
          AWS_REGION: ap-southeast-2
          AWS_ACCOUNT_ID: 039612872662
        run: |
          docker tag beyond/temp:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/beyond/temp:latest

      - name: Push Docker image to ECR
        env:
          AWS_REGION: ap-southeast-2
          AWS_ACCOUNT_ID: 039612872662
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/beyond/temp:latest
