name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build the Docker image
        run: docker build -t beyond/temp .

      - name: Tag the Docker image
        run: docker tag beyond/temp:latest 039612872662.dkr.ecr.ap-southeast-2.amazonaws.com/beyond/temp:latest

      - name: Push the Docker image
        run: docker push 039612872662.dkr.ecr.ap-southeast-2.amazonaws.com/beyond/temp:latest
